// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: ljaqmbzbngwhttlwzrqa

class SupabaseConfig {
  static const String supabaseUrl = 'https://ljaqmbzbngwhttlwzrqa.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqYXFtYnpibmd3aHR0bHd6cnFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2Njc1MDAsImV4cCI6MjA3MjI0MzUwMH0.ftQAPl3w-3KrSeQdX-wBxjMmMX-ozOS5rLFbpqcd_t4';
}
